import Link from 'next/link'; import {applicationAreas,currentMembers,latestNews,projects,researchThemes} from '@/data/site';
export default function Home(){return <>
<section className="hero"><div className="hero-media"><img src="/assets/research/Research01.jpeg" alt="Immersive XR interaction"/><div className="hero-shade"/></div><div className="wrap hero-content"><div className="eyebrow light">Human-X Interaction Lab · University of Calgary</div><h1>Augmenting human capability<br/>through <em>XR + AI.</em></h1><p>We design and study immersive, intelligent, and human-centered technologies that transform how people interact, learn, collaborate, and make decisions.</p><div className="hero-actions"><Link className="btn primary" href="/research">Explore Research</Link><Link className="btn ghost" href="/projects">View Projects</Link></div><div className="human-x"><span>HUMAN × XR</span><span>HUMAN × AI</span><span>HUMAN × AGENTS</span></div></div></section>
<section className="section intro"><div className="wrap split"><div><div className="eyebrow">Our Research</div><h2>Technology should extend human capability—not replace human judgment.</h2></div><p>HXI Lab investigates the design and effects of extended reality and artificial intelligence across social interaction, healthcare, training, wellbeing, and complex operational environments. We combine systems research with rigorous human-subject evaluation.</p></div></section>
<section className="section soft"><div className="wrap"><div className="section-title"><div><div className="eyebrow">What we study</div><h2>Research themes</h2></div><Link className="text-link" href="/research">Research overview →</Link></div><div className="theme-grid">{researchThemes.slice(0,4).map((r,i)=><article className="theme-card" key={r.title}><img src={r.image} alt=""/><div className="theme-overlay"><span>0{i+1}</span><div><small>{r.kicker}</small><h3>{r.title}</h3></div></div></article>)}</div></div></section>
<section className="section dark"><div className="wrap"><div className="section-title inverted"><div><div className="eyebrow light">Current work</div><h2>Featured projects</h2></div><Link className="text-link light-link" href="/projects">All projects →</Link></div><div className="project-grid">{projects.slice(0,4).map(p=><article className="project-card" key={p.title}><img src={p.image} alt=""/><div className="project-copy"><small>{p.label}</small><h3>{p.title}</h3><p>{p.text}</p><div className="project-meta">{p.meta}</div></div></article>)}</div></div></section>
<section className="section"><div className="wrap"><div className="section-title"><div><div className="eyebrow">Applications</div><h2>Where our work matters</h2></div></div><div className="application-grid">{applicationAreas.map(a=><article key={a.title}><img src={a.image} alt=""/><h3>{a.title}</h3><p>{a.text}</p></article>)}</div></div></section>
<section className="section soft"><div className="wrap split-news"><div><div className="eyebrow">Latest</div><h2>News from HXI</h2><Link className="text-link" href="/news">View all news →</Link></div><div className="news-list compact">{latestNews.slice(0,6).map(n=><div className="news-item" key={n.date+n.title}><div><span className="news-tag">{n.tag}</span><time>{n.date}</time></div><h3>{n.title}</h3></div>)}</div></div></section>
<section className="section"><div className="wrap"><div className="section-title"><div><div className="eyebrow">Team</div><h2>People behind the work</h2></div><Link className="text-link" href="/team">Meet the team →</Link></div><div className="people-strip">{currentMembers.slice(0,6).map(m=><article key={m.name}><img src={m.image} alt={m.name}/><h3>{m.name}</h3><p>{m.role}</p></article>)}</div></div></section>
<section className="join-cta"><div className="wrap"><div><div className="eyebrow light">Join HXI</div><h2>Build the next generation of human-centered immersive intelligence.</h2></div><Link className="btn white" href="/join">Opportunities & How to Apply</Link></div></section>
</>}
