import Link from 'next/link';
import {applicationAreas,currentMembers,latestNews,projects,researchThemes} from '@/data/site';

const xDimensions = [
  {title:'Human × XR', text:'Immersive and spatial interfaces that extend how people perceive, act, learn, and collaborate.', image:'/assets/research/Research01.jpeg'},
  {title:'Human × AI', text:'Intelligent systems and agents that support people without displacing judgment, agency, or meaningful control.', image:'/assets/research/Research03.jpeg'},
  {title:'Human × Intelligence', text:'Adaptive, affect-aware, and decision-support systems that augment human capability and expertise.', image:'/assets/research/Research05.jpeg'},
  {title:'Human × Technology', text:'New relationships among people, machines, environments, and emerging interactive systems.', image:'/assets/research/Research06.jpeg'},
];

export default function Home(){return <>
<section className="hero"><div className="hero-media"><img src="/assets/research/Research01.jpeg" alt="Immersive XR interaction"/><div className="hero-shade"/></div><div className="wrap hero-content"><div className="eyebrow light">HXIL · Human-X Interaction Lab · University of Calgary</div><h1><em>X is the variable.</em><br/>Human is the constant.</h1><p>At HXIL, X represents the evolving counterparts with which humans interact—from XR and AI to intelligent agents, machines, environments, and other people. We design and study these interactions to augment human capability while preserving judgment, agency, and meaningful experience.</p><div className="hero-actions"><Link className="btn primary" href="/research">Explore Research</Link><Link className="btn ghost" href="/projects">View Projects</Link></div><div className="human-x"><span>HUMAN × INTELLIGENCE</span><span>HUMAN × XR</span><span>HUMAN × AI</span><span>HUMAN × TECHNOLOGY</span></div></div></section>
<section className="section intro"><div className="wrap"><div className="split"><div><div className="eyebrow">The idea behind X</div><h2>We study what happens when humans meet an evolving X.</h2></div><p>Human-X Interaction is intentionally open-ended. X can be a technology, an intelligent agent, another person, a machine, or an environment. What stays constant is our focus on people: how they perceive, decide, collaborate, trust, learn, and retain meaningful control.</p></div><div className="x-dimension-grid">{xDimensions.map(x=><article className="x-dimension-card" key={x.title}><img src={x.image} alt=""/><div className="x-dimension-copy"><h3>{x.title}</h3><p>{x.text}</p></div></article>)}</div></div></section>
<section className="section soft"><div className="wrap"><div className="section-title"><div><div className="eyebrow">What we study</div><h2>Research themes</h2></div><Link className="text-link" href="/research">Research overview →</Link></div><div className="theme-grid">{researchThemes.slice(0,4).map((r,i)=><article className="theme-card" key={r.title}><img src={r.image} alt=""/><div className="theme-overlay"><span>0{i+1}</span><div><small>{r.kicker}</small><h3>{r.title}</h3></div></div></article>)}</div></div></section>
<section className="section dark"><div className="wrap"><div className="section-title inverted"><div><div className="eyebrow light">Current work</div><h2>Featured projects</h2></div><Link className="text-link light-link" href="/projects">All projects →</Link></div><div className="project-grid">{projects.slice(0,4).map(p=><article className="project-card" key={p.title}><img src={p.image} alt=""/><div className="project-copy"><small>{p.label}</small><h3>{p.title}</h3><p>{p.text}</p><div className="project-meta">{p.meta}</div></div></article>)}</div></div></section>
<section className="section"><div className="wrap"><div className="section-title"><div><div className="eyebrow">Applications</div><h2>Where our work matters</h2></div></div><div className="application-grid">{applicationAreas.map(a=><article key={a.title}><img src={a.image} alt=""/><h3>{a.title}</h3><p>{a.text}</p></article>)}</div></div></section>
<section className="section soft"><div className="wrap split-news"><div><div className="eyebrow">Latest</div><h2>News from HXIL</h2><Link className="text-link" href="/news">View all news →</Link></div><div className="news-list compact">{latestNews.slice(0,6).map(n=><div className="news-item" key={n.date+n.title}><div><span className="news-tag">{n.tag}</span><time>{n.date}</time></div><h3>{n.title}</h3></div>)}</div></div></section>
<section className="section"><div className="wrap"><div className="section-title"><div><div className="eyebrow">Team</div><h2>People behind the work</h2></div><Link className="text-link" href="/team">Meet the team →</Link></div><div className="people-strip">{currentMembers.slice(0,6).map(m=><article key={m.name}><img src={m.image} alt={m.name}/><h3>{m.name}</h3><p>{m.role}</p></article>)}</div></div></section>
<section className="join-cta"><div className="wrap"><div><div className="eyebrow light">Join HXIL</div><h2>Help us explore what X can become—and what it should mean for people.</h2></div><Link className="btn white" href="/join">Opportunities & How to Apply</Link></div></section>
</>}
